/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GatewayControllerHealthCheckResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * Service is healthy
   */
  healthCheckResponse?: shared.HealthCheckResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const GatewayControllerHealthCheckResponse$inboundSchema: z.ZodType<
  GatewayControllerHealthCheckResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  HealthCheckResponse: shared.HealthCheckResponse$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "HealthCheckResponse": "healthCheckResponse",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type GatewayControllerHealthCheckResponse$Outbound = {
  ContentType: string;
  HealthCheckResponse?: shared.HealthCheckResponse$Outbound | undefined;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const GatewayControllerHealthCheckResponse$outboundSchema: z.ZodType<
  GatewayControllerHealthCheckResponse$Outbound,
  z.ZodTypeDef,
  GatewayControllerHealthCheckResponse
> = z.object({
  contentType: z.string(),
  healthCheckResponse: shared.HealthCheckResponse$outboundSchema.optional(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    healthCheckResponse: "HealthCheckResponse",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GatewayControllerHealthCheckResponse$ {
  /** @deprecated use `GatewayControllerHealthCheckResponse$inboundSchema` instead. */
  export const inboundSchema =
    GatewayControllerHealthCheckResponse$inboundSchema;
  /** @deprecated use `GatewayControllerHealthCheckResponse$outboundSchema` instead. */
  export const outboundSchema =
    GatewayControllerHealthCheckResponse$outboundSchema;
  /** @deprecated use `GatewayControllerHealthCheckResponse$Outbound` instead. */
  export type Outbound = GatewayControllerHealthCheckResponse$Outbound;
}

export function gatewayControllerHealthCheckResponseToJSON(
  gatewayControllerHealthCheckResponse: GatewayControllerHealthCheckResponse,
): string {
  return JSON.stringify(
    GatewayControllerHealthCheckResponse$outboundSchema.parse(
      gatewayControllerHealthCheckResponse,
    ),
  );
}

export function gatewayControllerHealthCheckResponseFromJSON(
  jsonString: string,
): SafeParseResult<GatewayControllerHealthCheckResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GatewayControllerHealthCheckResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GatewayControllerHealthCheckResponse' from JSON`,
  );
}
