/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GatewayControllerProcessEngineRequestResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * Request processed successfully
   */
  engineProcessResponse?: shared.EngineProcessResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const GatewayControllerProcessEngineRequestResponse$inboundSchema:
  z.ZodType<
    GatewayControllerProcessEngineRequestResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    EngineProcessResponse: shared.EngineProcessResponse$inboundSchema
      .optional(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "EngineProcessResponse": "engineProcessResponse",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
    });
  });

/** @internal */
export type GatewayControllerProcessEngineRequestResponse$Outbound = {
  ContentType: string;
  EngineProcessResponse?: shared.EngineProcessResponse$Outbound | undefined;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const GatewayControllerProcessEngineRequestResponse$outboundSchema:
  z.ZodType<
    GatewayControllerProcessEngineRequestResponse$Outbound,
    z.ZodTypeDef,
    GatewayControllerProcessEngineRequestResponse
  > = z.object({
    contentType: z.string(),
    engineProcessResponse: shared.EngineProcessResponse$outboundSchema
      .optional(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      engineProcessResponse: "EngineProcessResponse",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GatewayControllerProcessEngineRequestResponse$ {
  /** @deprecated use `GatewayControllerProcessEngineRequestResponse$inboundSchema` instead. */
  export const inboundSchema =
    GatewayControllerProcessEngineRequestResponse$inboundSchema;
  /** @deprecated use `GatewayControllerProcessEngineRequestResponse$outboundSchema` instead. */
  export const outboundSchema =
    GatewayControllerProcessEngineRequestResponse$outboundSchema;
  /** @deprecated use `GatewayControllerProcessEngineRequestResponse$Outbound` instead. */
  export type Outbound = GatewayControllerProcessEngineRequestResponse$Outbound;
}

export function gatewayControllerProcessEngineRequestResponseToJSON(
  gatewayControllerProcessEngineRequestResponse:
    GatewayControllerProcessEngineRequestResponse,
): string {
  return JSON.stringify(
    GatewayControllerProcessEngineRequestResponse$outboundSchema.parse(
      gatewayControllerProcessEngineRequestResponse,
    ),
  );
}

export function gatewayControllerProcessEngineRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GatewayControllerProcessEngineRequestResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GatewayControllerProcessEngineRequestResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GatewayControllerProcessEngineRequestResponse' from JSON`,
  );
}
