apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: jackpot/admin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
              name: grpc
            - containerPort: 3004
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: GRPC_PORT
              value: "5004"
            - name: HTTP_PORT
              value: "3004"
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DATABASE_NAME
              value: "jackpot"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: METRICS_HOST
              value: "metrics"
            - name: METRICS_PORT
              value: "5002"
            - name: SCHEDULER_HOST
              value: "scheduler"
            - name: SCHEDULER_PORT
              value: "5003"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: jwt-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: refresh-token-secret
            - name: ADMIN_FRONTEND_URL
              value: "http://admin-frontend"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
    - port: 5004
      name: grpc
      targetPort: grpc
    - port: 3004
      name: http
      targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=  # base64 encoded "super-secret-jwt-key"
  refresh-token-secret: c3VwZXItc2VjcmV0LXJlZnJlc2gta2V5=  # base64 encoded "super-secret-refresh-key"
