apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
  labels:
    app: engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: jackpot/engine:latest
        ports:
        - containerPort: 5000
          name: grpc
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database
        - name: REDIS_HOST
          value: "redis-engine"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  labels:
    app: engine
spec:
  type: ClusterIP
  selector:
    app: engine
  ports:
  - port: 5000
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
