/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Gateway } from "./gateway.js";

export class JackpotAPI extends ClientSDK {
  private _gateway?: Gateway;
  get gateway(): Gateway {
    return (this._gateway ??= new Gateway(this._options));
  }
}
